import type { ExportProfile } from './profileTypes.js';

export const genericProfiles: ExportProfile[] = [
    {
        dataType: 'race',
        sourceFile: 'races.json',
        rootKey: 'race',
        fluffFile: 'fluff-races.json',
        fluffRootKey: 'raceFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'background',
        sourceFile: 'backgrounds.json',
        rootKey: 'background',
        fluffFile: 'fluff-backgrounds.json',
        fluffRootKey: 'backgroundFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'deity',
        sourceFile: 'deities.json',
        rootKey: 'deity',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'trap',
        sourceFile: 'trapshazards.json',
        rootKey: 'trap',
        fluffFile: 'fluff-trapshazards.json',
        fluffRootKey: 'trapFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'hazard',
        sourceFile: 'trapshazards.json',
        rootKey: 'hazard',
        fluffFile: 'fluff-trapshazards.json',
        fluffRootKey: 'hazardFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'vehicle',
        sourceFile: 'vehicles.json',
        rootKey: 'vehicle',
        fluffFile: 'fluff-vehicles.json',
        fluffRootKey: 'vehicleFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'vehicleUpgrade',
        sourceFile: 'vehicles.json',
        rootKey: 'vehicleUpgrade',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'variantrule',
        sourceFile: 'variantrules.json',
        rootKey: 'variantrule',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'monsterfeature',
        sourceFile: 'monsterfeatures.json',
        rootKey: 'monsterfeatures',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'optionalfeature',
        sourceFile: 'optionalfeatures.json',
        rootKey: 'optionalfeature',
        fluffFile: 'fluff-optionalfeatures.json',
        fluffRootKey: 'optionalfeatureFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'condition',
        sourceFile: 'conditionsdiseases.json',
        rootKey: 'condition',
        fluffFile: 'fluff-conditionsdiseases.json',
        fluffRootKey: 'conditionFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'disease',
        sourceFile: 'conditionsdiseases.json',
        rootKey: 'disease',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'language',
        sourceFile: 'languages.json',
        rootKey: 'language',
        fluffFile: 'fluff-languages.json',
        fluffRootKey: 'languageFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'skill',
        sourceFile: 'skills.json',
        rootKey: 'skill',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'sense',
        sourceFile: 'senses.json',
        rootKey: 'sense',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'charoption',
        sourceFile: 'charcreationoptions.json',
        rootKey: 'charoption',
        fluffFile: 'fluff-charcreationoptions.json',
        fluffRootKey: 'charoptionFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'bastion',
        sourceFile: 'bastions.json',
        rootKey: 'facility',
        fluffFile: 'fluff-bastions.json',
        fluffRootKey: 'facilityFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
        forceLocalizedKeys: ['prerequisite'],
    },
    {
        dataType: 'deck',
        sourceFile: 'decks.json',
        rootKey: 'deck',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'cult',
        sourceFile: 'cultsboons.json',
        rootKey: 'cult',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'boon',
        sourceFile: 'cultsboons.json',
        rootKey: 'boon',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'recipe',
        sourceFile: 'recipes.json',
        rootKey: 'recipe',
        fluffFile: 'fluff-recipes.json',
        fluffRootKey: 'recipeFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'reward',
        sourceFile: 'rewards.json',
        rootKey: 'reward',
        fluffFile: 'fluff-rewards.json',
        fluffRootKey: 'rewardFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'object',
        sourceFile: 'objects.json',
        rootKey: 'object',
        fluffFile: 'fluff-objects.json',
        fluffRootKey: 'objectFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'psionic',
        sourceFile: 'psionics.json',
        rootKey: 'psionic',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
    {
        dataType: 'homecraft',
        sourceFile: 'homecrafts.json',
        rootKey: 'crochetPattern',
        fluffFile: 'fluff-homecrafts.json',
        fluffRootKey: 'crochetPatternFluff',
        outputMode: 'file',
        i18nStrategy: 'deep-first-level',
    },
];
